### ISSUE TITLE
Unable to add server 

### ISSUE THREAD

**Issue by bobsage123** [teal77/trireme#11]
Hello when I try to add my server I enter the host and the port and hit continue  it just loads and loads and nothing happens. Assistance is appreciated.

**Comment by teal77** [comment]
How long does it stay that way? It times out at 30 second for me.

**Comment by bobsage123** [comment]
Longer than 30 seconds. It will keep going if i dont stop it.

**Comment by teal77** [comment]
I see, looks like a bug. What is your deluge version?

**Comment by teal77** [comment]
Ah, this app doesn't work through the web client interface. It acts as a regular thin client.
I don't know about seedboxes but this is how its done for regular torrent boxes. https://dev.deluge-torrent.org/wiki/UserGuide/ThinClient
