### ISSUE TITLE
no keyboard

### ISSUE THREAD

**Issue by dga4130-renato** [teal77/trireme#15]
The app doesn't call the keyboard up, unable to enter any data

**Comment by teal77** [comment]
Which screen?

**Comment by dga4130-renato** [comment]
Everyone

**Comment by dga4130-renato** [comment]
Managed to use paste and copied in the data. Logon success with 2.0.0 dev

**Comment by teal77** [comment]
It's working for me. Android version?

**Comment by dga4130-renato** [comment]
9

**Comment by dga4130-renato** [comment]
Galaxy S5 lineages 16 gboard

**Comment by dga4130-renato** [comment]
Amazing ... Was driving but had to stop after I saw what this app does. There are a few things maybe could be better but it's really done well and worth to use. I believe you could upload it on apkmirror and would increase even the deluge installation.

**Comment by dga4130-renato** [comment]
Btw previous version keyboard was working

**Comment by teal77** [comment]
Yeah, it was a bug with flutter. I'm compiling the app with latest beta version.

**Comment by dga4130-renato** [comment]
Btw can the option screen be skipped when adding the torrents directly from the browser ?

**Comment by teal77** [comment]
> Btw can the option screen be skipped when adding the torrents directly from the browser ?

No, whats your use case?

**Comment by teal77** [comment]
[app.zip](https://github.com/teal77/trireme/files/2788499/app.zip)
See if this fixes the keyboard

**Comment by teal77** [comment]
No, feedback is welcome!
The add flow was copied from deluge desktop, where it does give the user a chance to change the settings before add.
I wonder which one is better.

**Comment by dga4130-renato** [comment]
> No, feedback is welcome!
> The add flow was copied from deluge desktop, where it does give the user a chance to change the settings before add.
> I wonder which one is better.

well in my life of programmer in my young time i would make an option.... on for select options, off direct add with delaults, but still with the add options as buttons that work like in trabsdroid.
