### ISSUE TITLE
removing torrent

### ISSUE THREAD

**Issue by dga4130-renato** [teal77/trireme#16]
Selecting remove torrent and/or remove with data causes a black screen . If you press home button on the phone and call again the app the torrent is removed

**Comment by teal77** [comment]
Why? I saw it too xD

**Comment by teal77** [comment]
Strange, it happened like 2-3 times but it hasnt happned since

**Comment by dga4130-renato** [comment]
Same here . Btw I'm beta tester for deluge dev and tester of transdroid. I use these programs at least 20 times day.

**Comment by dga4130-renato** [comment]
Did u compile yet ? I don't see any new release

**Comment by teal77** [comment]
I left a comment in that issue. Thanks for your help btw!

**Comment by dga4130-renato** [comment]
Np. Get ready I will be here more than you can think now😂😂
