### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by dga4130-renato** [teal77/trireme#17]
Would be a nice implementation getting material dark mode as many apps support it now.
This would need white text and black background... text might have a colour choice and a selector in config that reads the default phone theme so if it is dark mode the switch will be done automatically..or manually

**Comment by teal77** [comment]
fb3e6935f04192907c1caf6d9d4591feffd42be2 adds dark mode and a setting to toggle dark mode in the app.

**Comment by dga4130-renato** [comment]
nice shot this one !
