### ISSUE TITLE
add by hash

### ISSUE THREAD

**Issue by dga4130-renato** [teal77/trireme#21]
button torrent add from info hash

**Comment by teal77** [comment]
Before I do this, I'm waiting for a proper speed dialer library that would work in docked mode.
https://material.io/design/components/buttons-floating-action-button.html#types-of-transitions
There are a couple of implementations now, but they don't work in docked mode.

**Comment by dga4130-renato** [comment]
That looks pretty nice . Pick an issue if you have extra time and let's
show what can be done..

Il sab 20 apr 2019, 11:59 Aashrava Holla <notifications@github.com> ha
scritto:
