### ISSUE TITLE
App repeatedly crashes after latest update

### ISSUE THREAD

**Issue by tommyguitfiddle** [teal77/trireme#22]
1.0.2 does not work for me.  It will open, but after adding my server it crashes.  Using android 8.0.0 and my server is a FreeNAS BSD jail.  Not sure of the server version of deluge, but I can get it if you think it's relevant.

**Comment by teal77** [comment]
Yes please give the Deluge version.

**Comment by tommyguitfiddle** [comment]
1.3.15

**Comment by teal77** [comment]
Can't reproduce here. Can you take a screenshot of the crash? Where exactly does it crash?

**Comment by tommyguitfiddle** [comment]
It crashes upon opening.  When I enter the server info and hit continue at the login info, I just get a system message saying the app has crashed.  Then if I try to open it again, it crashes immediately.  If I clear data, it will allow me to enter server info again, but crashes afterward.  I can get a screenshot, but it's just the standard android "deluge has crashed." message

**Comment by teal77** [comment]
Not sure how to proceed tbh. For now you can downgrade to 0.9.1

If you're up for it, I'll post a build with some sort of crash reporting library embedded.

**Comment by tommyguitfiddle** [comment]
https://tommyg.dyndns.org/nextcloud/index.php/s/w96Dn9gxJqmzBrx

**Comment by tommyguitfiddle** [comment]
I'm willing to try a version with better reporting if you think it will help.  I'll downgrade for now.  Love the app, so I'm hopeful I can get you the info you need to fix the bug.

**Comment by teal77** [comment]
Let's see if this works
[app.zip](https://github.com/teal77/trireme/files/2803344/app.zip)

**Comment by tommyguitfiddle** [comment]
I get the same result with that version.  Didn't see an option to save a crash report

**Comment by teal77** [comment]
So as I thought the crash seems to be in native layer since ACRA cant seem to capture it.
If anyone else has the same crash please leave a comment. Our best bet is to hope that it magically goes away in the next version.

**Comment by dhanushkuchki** [comment]
Hey, I wanted to leave a comment because I have been facing the same issue after the update yesterday. I am using the app on Android Pie. My deluge server version is 1.3.13. The app crashed right after launch after update to 1.0.2. I tried reinstalling it and this time it crashed right after adding my server it. 
Here's the logcat. Hope it helps : [Logcat] (https://gist.github.com/dhanushkuchki/9fa32f00123ebffd529139046dc51432)

Ask me if you need any other info regarding the crash. Thanks a lot for the amazing app. I will downgrade for now.

**Comment by dhanushkuchki** [comment]
It's working perfectly now without any crashes. Thanks for the quick fix!
