### ISSUE TITLE
Cannot add server 

### ISSUE THREAD

**Issue by shomilsaini** [teal77/trireme#28]
Tried the app.. looks promising but cannot even add server either local or over internet.
Btw still using transdrone so i know server/network setups are ok.

**Comment by shomilsaini** [comment]
It asks for mandatory username and password and I'm using binhex-delugevpn container which doesnot have that... We only have webui password. Is there a way around? Also my port 58846 is not exposed to internet... Transdrone uses default port 8112 or whatever i map to internet....

**Comment by teal77** [comment]
This app doesn't use web UI. You can either stick with transdrone or use the thin client setup. 
Don't know the specifics of your setup but here's how you do it for regular clients.
https://dev.deluge-torrent.org/wiki/UserGuide/ThinClient

**Comment by teal77** [comment]
I don't know about docker and stuff sorry. If the app is working in LAN, then you should consider using ssh tunnel instead of opening up the deluge port to the wider internet.
https://dev.deluge-torrent.org/wiki/UserGuide/ThinClient#CreateSSHTunnel
#7

**Comment by shomilsaini** [comment]
Ok so the issue with that ssh tunneling is that I'm behind multiple layers from public ip. That sectio. In that document assumes that you are on a machine directly connected to internet via a static ip.
For me the public ip is dynamic and resides with the internet company modem. Behind that i have local network lets say 192.168.xx.xx then my server has that class of ip. Then behind that inside docker i have another layer of network lets say 172.168.xx.xx and delige docker gets one of those on eth0. Also sinve deluge is vpn docker I'm using vpn so actual communication happens over vpn tunnel which is tun0 and there is a loopback lo0.
Any thoughts?

**Comment by teal77** [comment]
> Any thoughts?

Good luck I guess :smile: 

I personally only use the app in LAN so all this is beyond me.

**Comment by shomilsaini** [comment]
I have to say I like the app on LAN. But I'm going to have to figure out the remote access part.
Thanks for your efforts. I hope you keep on doing the good work.
Cheers!

**Comment by teal77** [comment]
Thanks!
I will probably add some kind of warning when users enter the web UI address in a future version.
#29

**Comment by shomilsaini** [comment]
I would suggest you to add the app in Google play store... also recommended you commit close issues without actually having a solution.

**Comment by teal77** [comment]
App was in play store at the beginning, but then google banned my account for no reason.
As for this issue there is nothing I can do here.
