### ISSUE TITLE
Not a subtype of type 'bool'

### ISSUE THREAD

**Issue by vesuvian** [teal77/trireme#31]
When going to the options page for a torrent i am getting the following error that is preventing the options page from rendering:

"Type '_Smi' is not a subtype of type 'bool' in type cast"

**Comment by teal77** [comment]
Does it happen always? Or occasionally? Can you post your deluge version? Sorry for not getting back.

**Comment by vesuvian** [comment]
Hey Teal77

I'm using 0.9.1

It was happening consistently for all torrents, but now I'm trying today it seems to be working just fine!

I think you can probably close this issue.
