### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by dga4130-renato** [teal77/trireme#32]
Hello, would be nice if you could find some extra time and make some changes..
Fantastic app !

**Comment by teal77** [comment]
Do you have any specific features that you feel should be prioritized?

**Comment by dga4130-renato** [comment]
There is so many still opend that I can't decide . Dark mode and material would be nice .. but there are other things with mayor importance .. just push up what u can do

**Comment by teal77** [comment]
I uploaded a beta release with dark mode and #33

**Comment by dga4130-renato** [comment]
testing, looks really really nice

Il giorno dom 21 apr 2019 alle ore 12:15 Aashrava Holla <
notifications@github.com> ha scritto:

**Comment by teal77** [comment]
Known bug: Torrent details > Peers has some text fields which are not working in dark mode

**Comment by dga4130-renato** [comment]
maybe because text is black, there is another thing. in the new appearance
byte size unit ... kibibytes...

Il giorno dom 21 apr 2019 alle ore 14:17 Aashrava Holla <
notifications@github.com> ha scritto:

**Comment by teal77** [comment]
https://en.m.wikipedia.org/wiki/Kibibyte

That's what it's called, I didn't make it up lol

**Comment by dga4130-renato** [comment]
oooopsss

Il giorno dom 21 apr 2019 alle ore 14:46 Aashrava Holla <
notifications@github.com> ha scritto:
