### ISSUE TITLE
open .torrent Files automatic android

### ISSUE THREAD

**Issue by ApolloGods** [teal77/trireme#33]
I can open automatic .torrent files with deluge App, but torrent isn't in download?
Had to open add torrentfile and do insert in this way.. please change.
thx to devs for app

**Comment by teal77** [comment]
You're not the only one who asked this. I think we should change the behaviour of link/file opening to directly add instead of going through the add torrent screen.
This is also the behaviour in Transdroid/Transdrone so it will be consistent for users who are coming over from those apps.

**Comment by ApolloGods** [comment]
Thank you,
open .torrent files are patched with 1.1.0 version
runs like charm.
sometimes if i open again over multitasking, it shows no torrents.
after close and opening again everything is normal (connected).

ad:
the darkmode is fine, thx.

Thread resolved thx
