### ISSUE TITLE
Store last download folders path

### ISSUE THREAD

**Issue by TheXby** [teal77/trireme#38]
Hi,
Could you please add an option to store recent folders or folders preset?
Also is there option to choose in which folder need to download torrent?

**Comment by teal77** [comment]
>is there option to choose in which folder need to download torrent?

There is an option when adding torrent in app, which is missing in options screen. I'll add it there.

**Comment by dowodenum** [comment]
Adding to this, I'd be happy just if the "Set download path" field autofilled whatever the default path is.

On my plex/seedbox VPS, it's /home/dowodenum/files/ but I have to type that manually every time I want to sort something into Anime/Manga/Music/TV/Movies/Audiobooks/Comics etc. Gets a bit tiresome!

**Comment by teal77** [comment]
Empty is default I think, you should be using tags for frequently accessed locations.
