### ISSUE TITLE
download path text input

### ISSUE THREAD

**Issue by Soundtoxin** [teal77/trireme#4]
If I'm setting my path and make a mistake, moving left or hitting backspace seems to move several characters at once for some reason. I'm using a Gemini PDA, so landscape mode with a physical keyboard. Got the app from f-droid and it's up to date.

**Comment by teal77** [comment]
Does the app lag in that device?
Not sure what we can do here, probably a bug from Flutter.

**Comment by Soundtoxin** [comment]
No lag! Works great aside from this issue. It's annoying because I have to be very careful not to make typos, and I'm still adjusting to its keyboard.

**Comment by teal77** [comment]
Is the issue only with that specific text field or all text fields in the app?

**Comment by Soundtoxin** [comment]
Didn't think of that. It also happens in the torrent url field.

**Comment by teal77** [comment]
[tests.zip](https://github.com/teal77/trireme/files/2252668/tests.zip)
I created a couple of apps with just edittext (text fields) to test this.
could you take a look at them and see if you can reproduce the issue on your device?

**Comment by Soundtoxin** [comment]
Just tested. flutter-app-profile.apk has the same issue and native-app-debug.apk works fine!

**Comment by teal77** [comment]
Thanks, as I suspected, this seems to be an issue with how Flutter handles physical keyboards.
