### ISSUE TITLE
Can't connect Feral Deluge

### ISSUE THREAD

**Issue by samsepiol59** [teal77/trireme#50]
I tried connecting my cloudbox deluge, and it works perfectly.

Then I tried connecting feral's deluge and I can't get it to work - I've tried all the possible url combinations but it keeps saying the password is wrong... Although the password is the one in feral's summary page.

Is this a known issue?

**Comment by teal77** [comment]
I'm not familiar with feral. Can you try connecting with desktop client and see if it works?

**Comment by samsepiol59** [comment]
I will try thanks! Can connect no problems via web obviously, will try via desktop client and report back!

**Comment by samsepiol59** [comment]
'twas my issue - the daemon details are "hidden" from feral's summary page, to find them you need to run `printf "10.0.0.1\n$(hostname -f)\n$(whoami)\n$(sed -rn 's/(.*)"daemon_port": (.*),/\2/p' ~/.config/deluge/core.conf)\n$(sed -rn "s/$(whoami):(.*):(.*)/\1/p" ~/.config/deluge/auth)\n"` via CLI.

It works perfectly, thank you very much!
