### ISSUE TITLE
Add Torrent not working!

### ISSUE THREAD

**Issue by RaviPabari** [teal77/trireme#52]
Tried adding torrent with file and URL but file does not get added and the main page just shows loading and I tried adding the download path too :/ I have Android 10 on my samsung A6+

**Comment by teal77** [comment]
https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-10.4.0-amd64-netinst.iso.torrent

can you open this link?

**Comment by RaviPabari** [comment]
No I can't open it still showing loading. Send me your email id I'll record that and send it to you.

**Comment by teal77** [comment]
Can you see other torrents? Is this on first run?

**Comment by RaviPabari** [comment]
No I cannot see any other torrents added I tried 5-6 other torrent files. I tried other apps and there all those were added and were working but here it keeps showing loading on main page. I tried unistalling and reinstalling the app but still the same :/

**Comment by teal77** [comment]
Have you connected to a deluge server? This app doesn't download torrents
on its own. Its just a remote for deluge.

**Comment by RaviPabari** [comment]
Ohhh this is a remote for deluge that's why it's not adding torrent files. My bad sorry bro :/

**Comment by teal77** [comment]
No worries bro, I will fix the confusing "loading" text when there is no
connection.

**Comment by RaviPabari** [comment]
Yea that would be great and nice App btw ♥
