### ISSUE TITLE
white screen on app launch

### ISSUE THREAD

**Issue by 532910** [teal77/trireme#59]
White flash burns eyes:
![ScreenRecord-2020-12-12-02-22-51](https://user-images.githubusercontent.com/14617699/101964097-438f8a80-3c21-11eb-95d2-20e67beffc79.gif)
For example other apps like Orgzly, Binary Eye or Car Report has no flash.
v1.3.0, android 10

**Comment by teal77** [comment]
Fixed in a22b0d61367dd7523c6445ff2ebd7c025263daed

Show blue icon background color until the appropriate theme is loaded in
