### ISSUE TITLE
Add torrent from URL does not work

### ISSUE THREAD

**Issue by junpet** [teal77/trireme#9]
When I try to add torrent using URL nothing happens. However I tried only torrents from `nyaa.si`.

**Comment by teal77** [comment]
Yeah, it's a bug. It was introduced when I implemented opening magnet links.
It will be fixed in next release.

For now, you can still add by opening link from the browser using the app.

**Comment by kiam001** [comment]
When is the problem fixed?

**Comment by teal77** [comment]
Next release. Don't know when, I'm busy with irl stuff

**Comment by teal77** [comment]
Fixed in 1.0.0
